language: php
php:
    - 7.4

script:
    - vendor/bin/phpstan analyse -l 5 -c phpstan.neon src
    - vendor/bin/tester tests

before_script:
    - travis_retry composer install --no-interaction --prefer-dist

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
